# Generated by Django 4.0.4 on 2022-04-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimentalWebApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
