# Generated by Django 4.0.4 on 2022-04-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimentalWebApp', '0002_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cellNumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='userName',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='mor', max_length=100),
        ),
    ]
