# Generated by Django 4.0.4 on 2022-05-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimentalWebApp', '0003_patient_rename_username_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cellNumber',
        ),
    ]
