# Generated by Django 4.0.4 on 2022-05-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimentalWebApp', '0004_remove_patient_cellnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='patient',
            name='apartment',
            field=models.CharField(default='12', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='Test City', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='Test Land', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='floor',
            field=models.CharField(default='4', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(default='Test Street', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(default='01.01.2022'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='mor@mor.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='mor', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='mor', max_length=100),
        ),
    ]
