# Generated by Django 4.0.4 on 2022-05-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimentalWebApp', '0005_remove_patient_address_patient_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(max_length=10, primary_key='true', serialize=False),
        ),
    ]
