# Generated by Django 4.0.4 on 2022-05-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimentalWebApp', '0006_alter_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.AddField(
            model_name='patient',
            name='area',
            field=models.CharField(default='מרכז', max_length=20),
        ),
    ]
