# Generated by Django 4.0.4 on 2022-05-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimentalWebApp', '0007_remove_patient_email_patient_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
