# Generated by Django 4.0.4 on 2022-05-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimentalWebApp', '0008_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(max_length=10, primary_key='true', serialize=False),
        ),
    ]
