# Generated by Django 4.0.4 on 2022-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimentalWebApp', '0009_alter_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10)),
                ('test_id', models.IntegerField()),
                ('next_test_date', models.DateField()),
                ('next_test_info', models.CharField(max_length=200)),
                ('test_results', models.CharField(max_length=200)),
                ('has_permission', models.BooleanField()),
                ('test_scores', models.CharField(max_length=100)),
                ('was_scored', models.BooleanField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
