# Generated by Django 4.0.4 on 2022-06-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimentalWebApp', '0010_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='location',
        ),
        migrations.AddField(
            model_name='test',
            name='isInHospital',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
